name: Production Build
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version name for the release (e.g., 1.0.0)'
        required: true
      release_notes:
        description: 'Release notes for this version'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build the APK
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE_64 }}
          KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -d  > keystore.jks
          ./gradlew --no-daemon assembleRelease

      - name: Rename the APK
        run:
          mv app/build/outputs/apk/release/app-release.apk timeline_v${{ github.event.inputs.release_version }}.apk

      - name: Upload APK to Release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.event.inputs.release_version }}"
          name: "Release v${{ github.event.inputs.release_version }}"
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
          artifacts:
            timeline_v${{ github.event.inputs.release_version }}.apk



